### ISSUE TITLE
Random Blog Functionality

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/Commons-Toolbar#2]
The random blog button seems to now be the "Learning is Fun with Mrs. Black" button in firefox. It also no longer works if you are logged out. It looks like the redirect login code is conflicting with the Random Blog functionality.

**Comment by r-a-y** [comment]
It's due to running the blog recount feature in BuddyPress Tools.

It wiped out the entire BP user blogs table:
http://commons.hwdsb.on.ca/blogs/

The random blog feature relies on blogs recorded to that table.  You can try re-running the tool, but I'm guessing that will cause the admin white screen again.

I'll try to look into this some time tomorrow.

**Comment by mrjarbenne** [comment]
Oh wow. That's a bit of a bigger deal than the random blog functionality not working. Guess we will stay away from those tools.

**Comment by r-a-y** [comment]
Or I can try and make that tool more efficient in BP core so it will work properly ;)

**Comment by mrjarbenne** [comment]
If only we knew someone who worked on the BuddyPress dev team. :)

**Comment by r-a-y** [comment]
I can confirm that the random blog feature is working again after repopulating the blogs.
